### ISSUE TITLE
Gaussian distribution  (--key-pattern=G:G) stalls memtier on macOS (at least)

### ISSUE THREAD

**Issue by filipecosta90** [RedisLabs/memtier_benchmark#98] opened 2019-11-07 17:54 UTC
hi there, running memtier with the Gaussian distribution option on macOS is stalling it ( build with TLS support is disabled  ).
```
memtier_benchmark --hide-histogram  --key-pattern=G:G
```
Output:
```
$ memtier_benchmark --hide-histogram  --key-pattern=G:G 
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 0%,   0 secs]  4 threads:           0 ops,       0 (avg:       0) ops/sec, 0.00KB/sec (avg: 0.00KB/sec),   nan (avg:   nan) msec latency
```

**Comment by QingchenDang** [comment] 2021-04-29 15:17
Same problem. Does anyone know how to fix it?

**Comment by yossigo** [comment] 2021-06-16 13:10
@YaacovHazan Duplicate of #158?

**Comment by YaacovHazan** [comment] 2021-06-17 06:23
Closed, duplicate of #158

**Closed by YaacovHazan** 2021-06-17 06:23 UTC
