### ISSUE TITLE
Support for multiple memcached servers?

### ISSUE THREAD

**Issue by nikhilk** [RedisLabs/memtier_benchmark#81] opened 2019-05-01 23:34 UTC
Is it possible to configure the tool to work against a set of memcache servers, rather than being limited to a single one?

**Comment by yaacovhazan-Redislabs** [comment] 2019-05-02 10:28
hi @nikhilk, currently, memtier-benchmark doesn't support this option.

**Comment by nikhilk** [comment] 2019-05-02 20:29
Good to know I wasn't missing some existing option based on my read of the help text. Would this be interesting to track as a feature/ask?

**Comment by itamarhaber** [comment] 2019-05-06 09:14
Hello @nikhilk 

If I understand correctly, by "work against a set of memcache servers" you are referring to the cluster pattern that in MC is implemented entirely client-side. This currently isn't on our roadmap but let's keep this open as a feature request to gather more feedback (and possibly a PR ;)).

**Comment by nikhilk** [comment] 2019-05-07 00:11
Yes, that is the pattern.

While I personally think its interesting to have a proxy router rather than exposing individual servers in many cases, the reason I was using this benchmarking tool was (somewhat ironically) to compare the performance of a proxy based solution vs. a set of servers exposed to the client.

**Comment by yossigo** [comment] 2022-05-19 10:41
Duplicate of #15

**Closed by yossigo** 2022-05-19 10:41 UTC
Labels: feature-request
