### ISSUE TITLE
Running through a kubernetes pod.

### ISSUE THREAD

**Issue by SBehan0** [RedisLabs/memtier_benchmark#149] opened 2020-12-11 16:26 UTC
I've been trying to use memtier benchmark to test performance of a redis server on a kubernetes pod but it's giving a connection timed out error.

$ ./memtier_benchmark --hide-histogram -a $REDIS_USER -c 1 -n 1 -t 1 --tls
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
Connection error: Connection refused
[RUN #1 0%,   0 secs]  0 threads:           0 ops,       0 (avg:       0) ops/sec, 0.00KB/sec (avg: 0.00KB/sec),  0.00 (avg:  0.00) msec latency

1         Threads
1        Connections per thread
1         Requests per client

ALL STATS
============================================================================================================================
Type         Ops/sec     Hits/sec   Misses/sec    Avg. Latency     p50 Latency     p99 Latency   p99.9 Latency       KB/sec 
----------------------------------------------------------------------------------------------------------------------------
Sets            0.00          ---          ---             ---             ---             ---             ---         0.00 
Gets            0.00         0.00         0.00             ---             ---             ---             ---         0.00 
Waits           0.00          ---          ---             ---             ---             ---             ---          --- 
Totals          0.00         0.00         0.00            -nan         0.00000         0.00000         0.00000         0.00

Is it possible to do this. I've also tried it using the pods ip-address in -s but that only cause a short delay in the running.

**Comment by filipecosta90** [comment] 2020-12-11 16:38
Hi there @SBehan0 I noticed you're missing the server address parameter. Are you running the benchmark within the same pod of redis?

**Comment by SBehan0** [comment] 2020-12-11 16:53
@filipecosta90 I tried running it under the same server address but it only caused a delay between starting the tests and the connection attempt timing out. I usually enter and execute the pod in bash, is there a way to run memtier benchmark like that?

**Comment by filipecosta90** [comment] 2020-12-11 17:01
@SBehan0 can you please share the details of version ( redis-server ...4,5,6?..  ), topology (standalone, oss-cluster, enterprise ) of redis you're running. That should enable me to help you further.
If I understood correctly you want to run redis on a pod (s) and memtier_benchmark on another. right?

**Comment by SBehan0** [comment] 2020-12-13 11:25
@filipecosta90 We're using redis 6 on an oss-cluster topology. We already have redis running on a kubernetes pod and I'm looking to run memtier_benchmark on that pod in order to test it.

**Comment by abdelrady** [comment] 2022-06-17 07:48
I have this exact error on cluster mode. Testing from another VM in same virtual network. Running in same VM doesn't have this problem. Non-cluster mode also works fine between multiple VMs.

Any idea why this is happening?

**Comment by filipecosta90** [comment] 2022-06-17 08:11
@abdelrady notice that the error above `Connection refused` is caused by the user not having passed the proper host and port and consequently not being able to reach redis on the other pod. 
Please run with:
```
Connection and General Options:
  -s, --server=ADDR              Server address (default: localhost)
  -p, --port=PORT                Server port (default: 6379)
```
Closing this issue given the solution is simply passing the right conn detials

**Closed by filipecosta90** 2022-06-17 08:11 UTC
Labels: question

**Comment by filipecosta90** [comment] 2022-06-17 08:46
@abdelrady then it's 100% related to a missconfig of redis itself :) ( one solution is to bind the redis-server processes to proper IP and properly pass the IP addresses to redis-cli cluster create ).
